package pojos;
// Generated 29-ene-2018 10:54:37 by Hibernate Tools 4.3.1



/**
 * Comentarios generated by hbm2java
 */
public class Comentarios  implements java.io.Serializable {


     private Integer id;
     private int comentarios;

    public Comentarios() {
    }

    public Comentarios(int comentarios) {
       this.comentarios = comentarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(int comentarios) {
        this.comentarios = comentarios;
    }




}


