package pojos;
// Generated 29-ene-2018 10:54:37 by Hibernate Tools 4.3.1



/**
 * Coordinador generated by hbm2java
 */
public class Coordinador  implements java.io.Serializable {


     private Integer id;
     private String coordinador;

    public Coordinador() {
    }

    public Coordinador(String coordinador) {
       this.coordinador = coordinador;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCoordinador() {
        return this.coordinador;
    }
    
    public void setCoordinador(String coordinador) {
        this.coordinador = coordinador;
    }




}


