package pojos;
// Generated 29-ene-2018 10:54:37 by Hibernate Tools 4.3.1



/**
 * Dieta generated by hbm2java
 */
public class Dieta  implements java.io.Serializable {


     private Integer id;
     private String dieta;

    public Dieta() {
    }

    public Dieta(String dieta) {
       this.dieta = dieta;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDieta() {
        return this.dieta;
    }
    
    public void setDieta(String dieta) {
        this.dieta = dieta;
    }




}


