package pojos;
// Generated 29-ene-2018 10:54:37 by Hibernate Tools 4.3.1



/**
 * Fecha generated by hbm2java
 */
public class Fecha  implements java.io.Serializable {


     private String fecha;
     private String diaSemana;
     private String week;

    public Fecha() {
    }

    public Fecha(String fecha, String diaSemana, String week) {
       this.fecha = fecha;
       this.diaSemana = diaSemana;
       this.week = week;
    }
   
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public String getDiaSemana() {
        return this.diaSemana;
    }
    
    public void setDiaSemana(String diaSemana) {
        this.diaSemana = diaSemana;
    }
    public String getWeek() {
        return this.week;
    }
    
    public void setWeek(String week) {
        this.week = week;
    }




}


