package pojos;
// Generated 29-ene-2018 10:54:37 by Hibernate Tools 4.3.1



/**
 * Obras generated by hbm2java
 */
public class Obras  implements java.io.Serializable {


     private Integer id;
     private String obras;

    public Obras() {
    }

    public Obras(String obras) {
       this.obras = obras;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getObras() {
        return this.obras;
    }
    
    public void setObras(String obras) {
        this.obras = obras;
    }




}


