package pojos;
// Generated 29-ene-2018 10:54:37 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Parte generated by hbm2java
 */
public class Parte  implements java.io.Serializable {


     private int idParte;
     private Proyecto proyecto;
     private User user;
     private Date fecha;
     private String trabajado;
     private String coordinador;
     private String cliente;
     private String delegacion;
     private String obras;
     private String provincia;
     private String concepto;
     private String dieta;
     private String comentarios;

    public Parte() {
    }

	
    public Parte(int idParte, Proyecto proyecto, Date fecha, String trabajado, String coordinador, String cliente, String delegacion, String obras, String provincia, String concepto, String dieta, String comentarios) {
        this.idParte = idParte;
        this.proyecto = proyecto;
        this.fecha = fecha;
        this.trabajado = trabajado;
        this.coordinador = coordinador;
        this.cliente = cliente;
        this.delegacion = delegacion;
        this.obras = obras;
        this.provincia = provincia;
        this.concepto = concepto;
        this.dieta = dieta;
        this.comentarios = comentarios;
    }
    public Parte(int idParte, Proyecto proyecto, User user, Date fecha, String trabajado, String coordinador, String cliente, String delegacion, String obras, String provincia, String concepto, String dieta, String comentarios) {
       this.idParte = idParte;
       this.proyecto = proyecto;
       this.user = user;
       this.fecha = fecha;
       this.trabajado = trabajado;
       this.coordinador = coordinador;
       this.cliente = cliente;
       this.delegacion = delegacion;
       this.obras = obras;
       this.provincia = provincia;
       this.concepto = concepto;
       this.dieta = dieta;
       this.comentarios = comentarios;
    }
   
    public int getIdParte() {
        return this.idParte;
    }
    
    public void setIdParte(int idParte) {
        this.idParte = idParte;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getTrabajado() {
        return this.trabajado;
    }
    
    public void setTrabajado(String trabajado) {
        this.trabajado = trabajado;
    }
    public String getCoordinador() {
        return this.coordinador;
    }
    
    public void setCoordinador(String coordinador) {
        this.coordinador = coordinador;
    }
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }
    public String getDelegacion() {
        return this.delegacion;
    }
    
    public void setDelegacion(String delegacion) {
        this.delegacion = delegacion;
    }
    public String getObras() {
        return this.obras;
    }
    
    public void setObras(String obras) {
        this.obras = obras;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public String getDieta() {
        return this.dieta;
    }
    
    public void setDieta(String dieta) {
        this.dieta = dieta;
    }
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }




}


