package pojos;
// Generated 29-ene-2018 10:54:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private int id;
     private String proyecto;
     private Set partes = new HashSet(0);

    public Proyecto() {
    }

	
    public Proyecto(int id, String proyecto) {
        this.id = id;
        this.proyecto = proyecto;
    }
    public Proyecto(int id, String proyecto, Set partes) {
       this.id = id;
       this.proyecto = proyecto;
       this.partes = partes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(String proyecto) {
        this.proyecto = proyecto;
    }
    public Set getPartes() {
        return this.partes;
    }
    
    public void setPartes(Set partes) {
        this.partes = partes;
    }




}


