package pojos;
// Generated 29-ene-2018 10:54:37 by Hibernate Tools 4.3.1



/**
 * Trabajado generated by hbm2java
 */
public class Trabajado  implements java.io.Serializable {


     private Integer idTrabajado;
     private String trabajado;

    public Trabajado() {
    }

    public Trabajado(String trabajado) {
       this.trabajado = trabajado;
    }
   
    public Integer getIdTrabajado() {
        return this.idTrabajado;
    }
    
    public void setIdTrabajado(Integer idTrabajado) {
        this.idTrabajado = idTrabajado;
    }
    public String getTrabajado() {
        return this.trabajado;
    }
    
    public void setTrabajado(String trabajado) {
        this.trabajado = trabajado;
    }




}


