package pojos;
// Generated 29-ene-2018 10:54:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String apellido1;
     private String apellido2;
     private String dni;
     private String email;
     private String password;
     private boolean trabajador;
     private boolean coordinador;
     private Set partes = new HashSet(0);

    public User() {
    }

	
    public User(int id, String nombre, String apellido1, String apellido2, String dni, String email, String password, boolean trabajador, boolean coordinador) {
        this.id = id;
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.apellido2 = apellido2;
        this.dni = dni;
        this.email = email;
        this.password = password;
        this.trabajador = trabajador;
        this.coordinador = coordinador;
    }
    public User(int id, String nombre, String apellido1, String apellido2, String dni, String email, String password, boolean trabajador, boolean coordinador, Set partes) {
       this.id = id;
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.dni = dni;
       this.email = email;
       this.password = password;
       this.trabajador = trabajador;
       this.coordinador = coordinador;
       this.partes = partes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(boolean trabajador) {
        this.trabajador = trabajador;
    }
    public boolean isCoordinador() {
        return this.coordinador;
    }
    
    public void setCoordinador(boolean coordinador) {
        this.coordinador = coordinador;
    }
    public Set getPartes() {
        return this.partes;
    }
    
    public void setPartes(Set partes) {
        this.partes = partes;
    }




}


